[package]
edition = "2021"
name = "learn-rust"
version = "0.1.0"

[[bin]]
name = "learning-rust"
path = "src/10/_10_1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
